version: '3.8'

services:
  
  trainer:
    build: ./trainer
    restart: always
    ports:
      - "8000:8000"
    
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]

    volumes:
      - Models-data:/app/data


  predicter:
    build: ./predicter
    restart: always
    ports:
      - "8001:8000"
    
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - Models-data:/app/data



  converter:
    build: ./converter
    restart: always
    ports:
      - "8002:8000"
    
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]

  cleaner:
    build: ./cleaner

    restart: always
    ports:
      - "8003:8000"
    
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
volumes:
  Models-data: