version: '3.8'

services:
  
  naive-bayes-model:
    build: ./NaiveBayesModel
    restart: always
    ports:
      - "8000:8000"
    
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]

  converter:
    build: ./converter
    restart: always
    ports:
      - "8001:8000"
    
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]

  cleaner:
    build: ./cleaner

    restart: always
    ports:
      - "8002:8000"
    
    command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
