apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: naive-bayes-project
build:
  artifacts:
    - image: cleaner
      context: cleaner
      docker:
        dockerfile: Dockerfile
    - image: converter
      context: converter
      docker:
        dockerfile: Dockerfile
    - image: predicter
      context: predicter
      docker:
        dockerfile: Dockerfile
    - image: trainer
      context: trainer
      docker:
        dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
      - k8s
