apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: converter
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
        - name: converter
          image: converter:latest
          imagePullPolicy: Never
          command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: converter-service
spec:
  selector:
    app: converter
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
