apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/elastic-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
