apiVersion: v1
kind: PersistentVolume
metadata:
  name: models-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/models-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
