apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleaner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cleaner
  template:
    metadata:
      labels:
        app: cleaner
    spec:
      containers:
        - name: cleaner
          image: naivebayesproject-cleaner:latest
          imagePullPolicy: Never
          command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - containerPort: 8000

          volumeMounts:
            - mountPath: /app/logs
              name: logs

      volumes:
        - name: logs
          persistentVolumeClaim:
              claimName: logs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: cleaner-service
spec:
  selector:
    app: cleaner
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30003
  type: NodePort
