apiVersion: v1
kind: Secret
metadata:
  name: service-urls-secret
type: Opaque
data:
  API_GPT: aHR0cDovL3RyYWluZXItc2VydmljZTo4MDAwL2ZpdA==
  FIT_URL: aHR0cDovL3RyYWluZXItc2VydmljZTo4MDAwL2ZpdA==
  PREDICT_URL: aHR0cDovL3ByZWRpY3Rlci1zZXJ2aWNlOjgwMDAvUHJlZGljdGlvbg==
